aws:
  bucket: BigData_Project
  region: us-east-1

paths:
  raw_data: raw/bank_customer_segmentation/bank_data.csv
  processed_data: processed/bank_customer_segmentation/

models:
  kmeans_path: models/kmeans/
  rf_path: models/random_forest/

spark:
  app_name: Bank_Customer_Segmentation